#!/usr/bin/env bash
cd $(dirname $0)

CMAKE="cmake -G Ninja ."


export CC=gcc
export CXX=g++

$CMAKE -B build.tmp/gcc-debug \
    -DCMAKE_INSTALL_PREFIX=dist/gcc-debug

$CMAKE -B build.tmp/gcc-release \
    -DCMAKE_INSTALL_PREFIX=dist/gcc-release \
    -DCMAKE_BUILD_TYPE=Release


export CC=clang
export CXX=clang++

$CMAKE -B build.tmp/clang-debug \
    -DCMAKE_INSTALL_PREFIX=dist/clang-debug-libc++

$CMAKE -B build.tmp/clang-release \
    -DCMAKE_INSTALL_PREFIX=dist/clang-release-libc++ \
    -DCMAKE_BUILD_TYPE=Release


export CXXFLAGS=-stdlib=libc++

$CMAKE -B build.tmp/clang-debug-libc++ \
    -DCMAKE_INSTALL_PREFIX=dist/clang-debug-libc++

$CMAKE -B build.tmp/clang-release-libc++ \
    -DCMAKE_INSTALL_PREFIX=dist/clang-release-libc++ \
    -DCMAKE_BUILD_TYPE=Release


export CXXFLAGS="${CXXFLAGS} -fsanitize=address"

$CMAKE -B build.tmp/clang-debug-asan \
    -DCMAKE_INSTALL_PREFIX=dist/clang-debug-asan

$CMAKE -B build.tmp/clang-release-asan \
    -DCMAKE_INSTALL_PREFIX=dist/clang-release-asan \
    -DCMAKE_BUILD_TYPE=Release


$CMAKE -B build.tmp/clang-debug-pmr-asan \
    -DCMAKE_INSTALL_PREFIX=dist/clang-debug-asan \
    -DFELSPAR_FORCE_PMR=YES

$CMAKE -B build.tmp/clang-release-pmr-asan \
    -DCMAKE_INSTALL_PREFIX=dist/clang-release-asan \
    -DCMAKE_BUILD_TYPE=Release \
    -DFELSPAR_FORCE_PMR=YES
